// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: invoices.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Invoicesrpc {

  /// <summary>Holder for reflection information generated from invoices.proto</summary>
  public static partial class InvoicesReflection {

    #region Descriptor
    /// <summary>File descriptor for invoices.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static InvoicesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5pbnZvaWNlcy5wcm90bxILaW52b2ljZXNycGMaHGdvb2dsZS9hcGkvYW5u",
            "b3RhdGlvbnMucHJvdG8aCXJwYy5wcm90byIoChBDYW5jZWxJbnZvaWNlTXNn",
            "EhQKDHBheW1lbnRfaGFzaBgBIAEoDCITChFDYW5jZWxJbnZvaWNlUmVzcCLP",
            "AgoVQWRkSG9sZEludm9pY2VSZXF1ZXN0EhIKBG1lbW8YASABKAlSBG1lbW8S",
            "EgoEaGFzaBgCIAEoDFIEaGFzaBIUCgV2YWx1ZRgDIAEoA1IFdmFsdWUSHgoK",
            "dmFsdWVfbXNhdBgKIAEoA1IKdmFsdWVfbXNhdBIqChBkZXNjcmlwdGlvbl9o",
            "YXNoGAQgASgMUhBkZXNjcmlwdGlvbl9oYXNoEhYKBmV4cGlyeRgFIAEoA1IG",
            "ZXhwaXJ5EiQKDWZhbGxiYWNrX2FkZHIYBiABKAlSDWZhbGxiYWNrX2FkZHIS",
            "IAoLY2x0dl9leHBpcnkYByABKARSC2NsdHZfZXhwaXJ5EjIKC3JvdXRlX2hp",
            "bnRzGAggAygLMhAubG5ycGMuUm91dGVIaW50Ugtyb3V0ZV9oaW50cxIYCgdw",
            "cml2YXRlGAkgASgIUgdwcml2YXRlIj4KEkFkZEhvbGRJbnZvaWNlUmVzcBIo",
            "Cg9wYXltZW50X3JlcXVlc3QYASABKAlSD3BheW1lbnRfcmVxdWVzdCIkChBT",
            "ZXR0bGVJbnZvaWNlTXNnEhAKCHByZWltYWdlGAEgASgMIhMKEVNldHRsZUlu",
            "dm9pY2VSZXNwIj0KHVN1YnNjcmliZVNpbmdsZUludm9pY2VSZXF1ZXN0EhYK",
            "BnJfaGFzaBgCIAEoDFIGcl9oYXNoSgQIARACMtkCCghJbnZvaWNlcxJWChZT",
            "dWJzY3JpYmVTaW5nbGVJbnZvaWNlEiouaW52b2ljZXNycGMuU3Vic2NyaWJl",
            "U2luZ2xlSW52b2ljZVJlcXVlc3QaDi5sbnJwYy5JbnZvaWNlMAESTgoNQ2Fu",
            "Y2VsSW52b2ljZRIdLmludm9pY2VzcnBjLkNhbmNlbEludm9pY2VNc2caHi5p",
            "bnZvaWNlc3JwYy5DYW5jZWxJbnZvaWNlUmVzcBJVCg5BZGRIb2xkSW52b2lj",
            "ZRIiLmludm9pY2VzcnBjLkFkZEhvbGRJbnZvaWNlUmVxdWVzdBofLmludm9p",
            "Y2VzcnBjLkFkZEhvbGRJbnZvaWNlUmVzcBJOCg1TZXR0bGVJbnZvaWNlEh0u",
            "aW52b2ljZXNycGMuU2V0dGxlSW52b2ljZU1zZxoeLmludm9pY2VzcnBjLlNl",
            "dHRsZUludm9pY2VSZXNwQjNaMWdpdGh1Yi5jb20vbGlnaHRuaW5nbmV0d29y",
            "ay9sbmQvbG5ycGMvaW52b2ljZXNycGNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Lnrpc.RpcReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.CancelInvoiceMsg), global::Invoicesrpc.CancelInvoiceMsg.Parser, new[]{ "PaymentHash" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.CancelInvoiceResp), global::Invoicesrpc.CancelInvoiceResp.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.AddHoldInvoiceRequest), global::Invoicesrpc.AddHoldInvoiceRequest.Parser, new[]{ "Memo", "Hash", "Value", "ValueMsat", "DescriptionHash", "Expiry", "FallbackAddr", "CltvExpiry", "RouteHints", "Private" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.AddHoldInvoiceResp), global::Invoicesrpc.AddHoldInvoiceResp.Parser, new[]{ "PaymentRequest" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.SettleInvoiceMsg), global::Invoicesrpc.SettleInvoiceMsg.Parser, new[]{ "Preimage" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.SettleInvoiceResp), global::Invoicesrpc.SettleInvoiceResp.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Invoicesrpc.SubscribeSingleInvoiceRequest), global::Invoicesrpc.SubscribeSingleInvoiceRequest.Parser, new[]{ "RHash" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CancelInvoiceMsg : pb::IMessage<CancelInvoiceMsg> {
    private static readonly pb::MessageParser<CancelInvoiceMsg> _parser = new pb::MessageParser<CancelInvoiceMsg>(() => new CancelInvoiceMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CancelInvoiceMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelInvoiceMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelInvoiceMsg(CancelInvoiceMsg other) : this() {
      paymentHash_ = other.paymentHash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelInvoiceMsg Clone() {
      return new CancelInvoiceMsg(this);
    }

    /// <summary>Field number for the "payment_hash" field.</summary>
    public const int PaymentHashFieldNumber = 1;
    private pb::ByteString paymentHash_ = pb::ByteString.Empty;
    /// <summary>
    //// Hash corresponding to the (hold) invoice to cancel.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString PaymentHash {
      get { return paymentHash_; }
      set {
        paymentHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CancelInvoiceMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CancelInvoiceMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentHash != other.PaymentHash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentHash.Length != 0) hash ^= PaymentHash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PaymentHash.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(PaymentHash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PaymentHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(PaymentHash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CancelInvoiceMsg other) {
      if (other == null) {
        return;
      }
      if (other.PaymentHash.Length != 0) {
        PaymentHash = other.PaymentHash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentHash = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class CancelInvoiceResp : pb::IMessage<CancelInvoiceResp> {
    private static readonly pb::MessageParser<CancelInvoiceResp> _parser = new pb::MessageParser<CancelInvoiceResp>(() => new CancelInvoiceResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CancelInvoiceResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelInvoiceResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelInvoiceResp(CancelInvoiceResp other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CancelInvoiceResp Clone() {
      return new CancelInvoiceResp(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CancelInvoiceResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CancelInvoiceResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CancelInvoiceResp other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class AddHoldInvoiceRequest : pb::IMessage<AddHoldInvoiceRequest> {
    private static readonly pb::MessageParser<AddHoldInvoiceRequest> _parser = new pb::MessageParser<AddHoldInvoiceRequest>(() => new AddHoldInvoiceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddHoldInvoiceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddHoldInvoiceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddHoldInvoiceRequest(AddHoldInvoiceRequest other) : this() {
      memo_ = other.memo_;
      hash_ = other.hash_;
      value_ = other.value_;
      valueMsat_ = other.valueMsat_;
      descriptionHash_ = other.descriptionHash_;
      expiry_ = other.expiry_;
      fallbackAddr_ = other.fallbackAddr_;
      cltvExpiry_ = other.cltvExpiry_;
      routeHints_ = other.routeHints_.Clone();
      private_ = other.private_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddHoldInvoiceRequest Clone() {
      return new AddHoldInvoiceRequest(this);
    }

    /// <summary>Field number for the "memo" field.</summary>
    public const int MemoFieldNumber = 1;
    private string memo_ = "";
    /// <summary>
    ///*
    ///An optional memo to attach along with the invoice. Used for record keeping
    ///purposes for the invoice's creator, and will also be set in the description
    ///field of the encoded payment request if the description_hash field is not
    ///being used.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Memo {
      get { return memo_; }
      set {
        memo_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "hash" field.</summary>
    public const int HashFieldNumber = 2;
    private pb::ByteString hash_ = pb::ByteString.Empty;
    /// <summary>
    //// The hash of the preimage
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 3;
    private long value_;
    /// <summary>
    ///*
    ///The value of this invoice in satoshis
    ///
    ///The fields value and value_msat are mutually exclusive.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    /// <summary>Field number for the "value_msat" field.</summary>
    public const int ValueMsatFieldNumber = 10;
    private long valueMsat_;
    /// <summary>
    ///*
    ///The value of this invoice in millisatoshis
    ///
    ///The fields value and value_msat are mutually exclusive.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long ValueMsat {
      get { return valueMsat_; }
      set {
        valueMsat_ = value;
      }
    }

    /// <summary>Field number for the "description_hash" field.</summary>
    public const int DescriptionHashFieldNumber = 4;
    private pb::ByteString descriptionHash_ = pb::ByteString.Empty;
    /// <summary>
    ///*
    ///Hash (SHA-256) of a description of the payment. Used if the description of
    ///payment (memo) is too long to naturally fit within the description field
    ///of an encoded payment request.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString DescriptionHash {
      get { return descriptionHash_; }
      set {
        descriptionHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "expiry" field.</summary>
    public const int ExpiryFieldNumber = 5;
    private long expiry_;
    /// <summary>
    //// Payment request expiry time in seconds. Default is 3600 (1 hour).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Expiry {
      get { return expiry_; }
      set {
        expiry_ = value;
      }
    }

    /// <summary>Field number for the "fallback_addr" field.</summary>
    public const int FallbackAddrFieldNumber = 6;
    private string fallbackAddr_ = "";
    /// <summary>
    //// Fallback on-chain address.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FallbackAddr {
      get { return fallbackAddr_; }
      set {
        fallbackAddr_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "cltv_expiry" field.</summary>
    public const int CltvExpiryFieldNumber = 7;
    private ulong cltvExpiry_;
    /// <summary>
    //// Delta to use for the time-lock of the CLTV extended to the final hop.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong CltvExpiry {
      get { return cltvExpiry_; }
      set {
        cltvExpiry_ = value;
      }
    }

    /// <summary>Field number for the "route_hints" field.</summary>
    public const int RouteHintsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Lnrpc.RouteHint> _repeated_routeHints_codec
        = pb::FieldCodec.ForMessage(66, global::Lnrpc.RouteHint.Parser);
    private readonly pbc::RepeatedField<global::Lnrpc.RouteHint> routeHints_ = new pbc::RepeatedField<global::Lnrpc.RouteHint>();
    /// <summary>
    ///*
    ///Route hints that can each be individually used to assist in reaching the
    ///invoice's destination.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Lnrpc.RouteHint> RouteHints {
      get { return routeHints_; }
    }

    /// <summary>Field number for the "private" field.</summary>
    public const int PrivateFieldNumber = 9;
    private bool private_;
    /// <summary>
    //// Whether this invoice should include routing hints for private channels.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Private {
      get { return private_; }
      set {
        private_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddHoldInvoiceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddHoldInvoiceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Memo != other.Memo) return false;
      if (Hash != other.Hash) return false;
      if (Value != other.Value) return false;
      if (ValueMsat != other.ValueMsat) return false;
      if (DescriptionHash != other.DescriptionHash) return false;
      if (Expiry != other.Expiry) return false;
      if (FallbackAddr != other.FallbackAddr) return false;
      if (CltvExpiry != other.CltvExpiry) return false;
      if(!routeHints_.Equals(other.routeHints_)) return false;
      if (Private != other.Private) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Memo.Length != 0) hash ^= Memo.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (Value != 0L) hash ^= Value.GetHashCode();
      if (ValueMsat != 0L) hash ^= ValueMsat.GetHashCode();
      if (DescriptionHash.Length != 0) hash ^= DescriptionHash.GetHashCode();
      if (Expiry != 0L) hash ^= Expiry.GetHashCode();
      if (FallbackAddr.Length != 0) hash ^= FallbackAddr.GetHashCode();
      if (CltvExpiry != 0UL) hash ^= CltvExpiry.GetHashCode();
      hash ^= routeHints_.GetHashCode();
      if (Private != false) hash ^= Private.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Memo.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Memo);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(Hash);
      }
      if (Value != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Value);
      }
      if (DescriptionHash.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(DescriptionHash);
      }
      if (Expiry != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Expiry);
      }
      if (FallbackAddr.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(FallbackAddr);
      }
      if (CltvExpiry != 0UL) {
        output.WriteRawTag(56);
        output.WriteUInt64(CltvExpiry);
      }
      routeHints_.WriteTo(output, _repeated_routeHints_codec);
      if (Private != false) {
        output.WriteRawTag(72);
        output.WriteBool(Private);
      }
      if (ValueMsat != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(ValueMsat);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Memo.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Memo);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
      }
      if (Value != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Value);
      }
      if (ValueMsat != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ValueMsat);
      }
      if (DescriptionHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(DescriptionHash);
      }
      if (Expiry != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Expiry);
      }
      if (FallbackAddr.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FallbackAddr);
      }
      if (CltvExpiry != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CltvExpiry);
      }
      size += routeHints_.CalculateSize(_repeated_routeHints_codec);
      if (Private != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddHoldInvoiceRequest other) {
      if (other == null) {
        return;
      }
      if (other.Memo.Length != 0) {
        Memo = other.Memo;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      if (other.Value != 0L) {
        Value = other.Value;
      }
      if (other.ValueMsat != 0L) {
        ValueMsat = other.ValueMsat;
      }
      if (other.DescriptionHash.Length != 0) {
        DescriptionHash = other.DescriptionHash;
      }
      if (other.Expiry != 0L) {
        Expiry = other.Expiry;
      }
      if (other.FallbackAddr.Length != 0) {
        FallbackAddr = other.FallbackAddr;
      }
      if (other.CltvExpiry != 0UL) {
        CltvExpiry = other.CltvExpiry;
      }
      routeHints_.Add(other.routeHints_);
      if (other.Private != false) {
        Private = other.Private;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Memo = input.ReadString();
            break;
          }
          case 18: {
            Hash = input.ReadBytes();
            break;
          }
          case 24: {
            Value = input.ReadInt64();
            break;
          }
          case 34: {
            DescriptionHash = input.ReadBytes();
            break;
          }
          case 40: {
            Expiry = input.ReadInt64();
            break;
          }
          case 50: {
            FallbackAddr = input.ReadString();
            break;
          }
          case 56: {
            CltvExpiry = input.ReadUInt64();
            break;
          }
          case 66: {
            routeHints_.AddEntriesFrom(input, _repeated_routeHints_codec);
            break;
          }
          case 72: {
            Private = input.ReadBool();
            break;
          }
          case 80: {
            ValueMsat = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  public sealed partial class AddHoldInvoiceResp : pb::IMessage<AddHoldInvoiceResp> {
    private static readonly pb::MessageParser<AddHoldInvoiceResp> _parser = new pb::MessageParser<AddHoldInvoiceResp>(() => new AddHoldInvoiceResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AddHoldInvoiceResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddHoldInvoiceResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddHoldInvoiceResp(AddHoldInvoiceResp other) : this() {
      paymentRequest_ = other.paymentRequest_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AddHoldInvoiceResp Clone() {
      return new AddHoldInvoiceResp(this);
    }

    /// <summary>Field number for the "payment_request" field.</summary>
    public const int PaymentRequestFieldNumber = 1;
    private string paymentRequest_ = "";
    /// <summary>
    ///*
    ///A bare-bones invoice for a payment within the Lightning Network.  With the
    ///details of the invoice, the sender has all the data necessary to send a
    ///payment to the recipient.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string PaymentRequest {
      get { return paymentRequest_; }
      set {
        paymentRequest_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AddHoldInvoiceResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AddHoldInvoiceResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PaymentRequest != other.PaymentRequest) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (PaymentRequest.Length != 0) hash ^= PaymentRequest.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (PaymentRequest.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(PaymentRequest);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (PaymentRequest.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PaymentRequest);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AddHoldInvoiceResp other) {
      if (other == null) {
        return;
      }
      if (other.PaymentRequest.Length != 0) {
        PaymentRequest = other.PaymentRequest;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            PaymentRequest = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SettleInvoiceMsg : pb::IMessage<SettleInvoiceMsg> {
    private static readonly pb::MessageParser<SettleInvoiceMsg> _parser = new pb::MessageParser<SettleInvoiceMsg>(() => new SettleInvoiceMsg());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettleInvoiceMsg> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettleInvoiceMsg() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettleInvoiceMsg(SettleInvoiceMsg other) : this() {
      preimage_ = other.preimage_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettleInvoiceMsg Clone() {
      return new SettleInvoiceMsg(this);
    }

    /// <summary>Field number for the "preimage" field.</summary>
    public const int PreimageFieldNumber = 1;
    private pb::ByteString preimage_ = pb::ByteString.Empty;
    /// <summary>
    //// Externally discovered pre-image that should be used to settle the hold invoice.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Preimage {
      get { return preimage_; }
      set {
        preimage_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettleInvoiceMsg);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettleInvoiceMsg other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Preimage != other.Preimage) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Preimage.Length != 0) hash ^= Preimage.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Preimage.Length != 0) {
        output.WriteRawTag(10);
        output.WriteBytes(Preimage);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Preimage.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Preimage);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettleInvoiceMsg other) {
      if (other == null) {
        return;
      }
      if (other.Preimage.Length != 0) {
        Preimage = other.Preimage;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Preimage = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SettleInvoiceResp : pb::IMessage<SettleInvoiceResp> {
    private static readonly pb::MessageParser<SettleInvoiceResp> _parser = new pb::MessageParser<SettleInvoiceResp>(() => new SettleInvoiceResp());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SettleInvoiceResp> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettleInvoiceResp() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettleInvoiceResp(SettleInvoiceResp other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SettleInvoiceResp Clone() {
      return new SettleInvoiceResp(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SettleInvoiceResp);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SettleInvoiceResp other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SettleInvoiceResp other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    }

  }

  public sealed partial class SubscribeSingleInvoiceRequest : pb::IMessage<SubscribeSingleInvoiceRequest> {
    private static readonly pb::MessageParser<SubscribeSingleInvoiceRequest> _parser = new pb::MessageParser<SubscribeSingleInvoiceRequest>(() => new SubscribeSingleInvoiceRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SubscribeSingleInvoiceRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Invoicesrpc.InvoicesReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeSingleInvoiceRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeSingleInvoiceRequest(SubscribeSingleInvoiceRequest other) : this() {
      rHash_ = other.rHash_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SubscribeSingleInvoiceRequest Clone() {
      return new SubscribeSingleInvoiceRequest(this);
    }

    /// <summary>Field number for the "r_hash" field.</summary>
    public const int RHashFieldNumber = 2;
    private pb::ByteString rHash_ = pb::ByteString.Empty;
    /// <summary>
    //// Hash corresponding to the (hold) invoice to subscribe to.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString RHash {
      get { return rHash_; }
      set {
        rHash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SubscribeSingleInvoiceRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SubscribeSingleInvoiceRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RHash != other.RHash) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (RHash.Length != 0) hash ^= RHash.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (RHash.Length != 0) {
        output.WriteRawTag(18);
        output.WriteBytes(RHash);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (RHash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(RHash);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SubscribeSingleInvoiceRequest other) {
      if (other == null) {
        return;
      }
      if (other.RHash.Length != 0) {
        RHash = other.RHash;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            RHash = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
